In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("airbnb_decision.csv")

In [3]:
print(dataset)

             id   host_id neighbourhood_group  latitude  longitude  price  \
0          2539      2787            Brooklyn  40.64749  -73.97237    149   
1          2595      2845           Manhattan  40.75362  -73.98377    225   
2          3647      4632           Manhattan  40.80902  -73.94190    150   
3          3831      4869            Brooklyn  40.68514  -73.95976     89   
4          5022      7192           Manhattan  40.79851  -73.94399     80   
...         ...       ...                 ...       ...        ...    ...   
48890  36484665   8232441            Brooklyn  40.67853  -73.94995     70   
48891  36485057   6570630            Brooklyn  40.70184  -73.93317     40   
48892  36485431  23492952           Manhattan  40.81475  -73.94867    115   
48893  36485609  30985759           Manhattan  40.75751  -73.99112     55   
48894  36487245  68119814           Manhattan  40.76404  -73.98933     90   

       minimum_nights  number_of_reviews  reviews_per_month  \
0           

In [4]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[2539 2787 'Brooklyn' ... 0.21 6 365]
 [2595 2845 'Manhattan' ... 0.38 2 355]
 [3647 4632 'Manhattan' ... nan 1 365]
 ...
 [36485431 23492952 'Manhattan' ... nan 1 27]
 [36485609 30985759 'Manhattan' ... nan 6 2]
 [36487245 68119814 'Manhattan' ... nan 1 23]]
['Yes' 'No' 'Yes' ... 'Yes' 'Yes' 'No']


In [5]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,5:11])
x[:,5:11] = imputer.transform(x[:, 5:11])


In [6]:
print(x)

[[2539 2787 'Brooklyn' ... 0.21 6.0 365.0]
 [2595 2845 'Manhattan' ... 0.38 2.0 355.0]
 [3647 4632 'Manhattan' ... 1.3732214298586618 1.0 365.0]
 ...
 [36485431 23492952 'Manhattan' ... 1.3732214298586618 1.0 27.0]
 [36485609 30985759 'Manhattan' ... 1.3732214298586618 6.0 2.0]
 [36487245 68119814 'Manhattan' ... 1.3732214298586618 1.0 23.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 ... 0.21 6.0 365.0]
 [0.0 0.0 1.0 ... 0.38 2.0 355.0]
 [0.0 0.0 1.0 ... 1.3732214298586618 1.0 365.0]
 ...
 [0.0 0.0 1.0 ... 1.3732214298586618 1.0 27.0]
 [0.0 0.0 1.0 ... 1.3732214298586618 6.0 2.0]
 [0.0 0.0 1.0 ... 1.3732214298586618 1.0 23.0]]


In [9]:
dataset['price'].describe()


count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=np.array(le.fit_transform(y))

In [11]:
print(y)

[1 0 1 ... 1 1 0]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 5:] = sc.fit_transform(x_train[:, 5:])
x_test[:, 5:] = sc.transform(x_test[:, 5:])

In [14]:
print(x_test)

[[0.0 0.0 0.0 ... 0.0015531839802429147 -0.15524466268660686
  -0.35133197325386173]
 [0.0 0.0 0.0 ... 0.0015531839802429147 -0.18535897077313954
  1.2932823048215825]
 [0.0 1.0 0.0 ... 0.5183844422245794 -0.18535897077313954
  -0.853853002665803]
 ...
 [0.0 1.0 0.0 ... 0.8776745799547697 -0.15524466268660686
  0.1816448761224396]
 [0.0 1.0 0.0 ... -0.1669282278904132 -0.15524466268660686
  -0.26757846835187155]
 [0.0 0.0 0.0 ... -0.5794465341732244 2.886300454053193
  1.1943008899374121]]


In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)