In [52]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [53]:
dataset=pd.read_csv("airbnb_decision.csv")

In [54]:
print(dataset)

             id   host_id neighbourhood_group  latitude  longitude  price  \
0          2539      2787            Brooklyn  40.64749  -73.97237    149   
1          2595      2845           Manhattan  40.75362  -73.98377    225   
2          3647      4632           Manhattan  40.80902  -73.94190    150   
3          3831      4869            Brooklyn  40.68514  -73.95976     89   
4          5022      7192           Manhattan  40.79851  -73.94399     80   
...         ...       ...                 ...       ...        ...    ...   
48890  36484665   8232441            Brooklyn  40.67853  -73.94995     70   
48891  36485057   6570630            Brooklyn  40.70184  -73.93317     40   
48892  36485431  23492952           Manhattan  40.81475  -73.94867    115   
48893  36485609  30985759           Manhattan  40.75751  -73.99112     55   
48894  36487245  68119814           Manhattan  40.76404  -73.98933     90   

       minimum_nights  number_of_reviews  reviews_per_month  \
0           

In [55]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[2539 2787 'Brooklyn' ... 0.21 6 365]
 [2595 2845 'Manhattan' ... 0.38 2 355]
 [3647 4632 'Manhattan' ... nan 1 365]
 ...
 [36485431 23492952 'Manhattan' ... nan 1 27]
 [36485609 30985759 'Manhattan' ... nan 6 2]
 [36487245 68119814 'Manhattan' ... nan 1 23]]
['Yes' 'No' 'Yes' ... 'Yes' 'Yes' 'No']


In [56]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,5:11])
x[:,5:11] = imputer.transform(x[:, 5:11])

In [57]:
print(x)

[[2539 2787 'Brooklyn' ... 0.21 6.0 365.0]
 [2595 2845 'Manhattan' ... 0.38 2.0 355.0]
 [3647 4632 'Manhattan' ... 1.3732214298586618 1.0 365.0]
 ...
 [36485431 23492952 'Manhattan' ... 1.3732214298586618 1.0 27.0]
 [36485609 30985759 'Manhattan' ... 1.3732214298586618 6.0 2.0]
 [36487245 68119814 'Manhattan' ... 1.3732214298586618 1.0 23.0]]


In [58]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = np.array(le.fit_transform(y))


In [59]:
print(y)

[1 0 1 ... 1 1 0]


In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [61]:
print(x)

[[0.0 1.0 0.0 ... 0.21 6.0 365.0]
 [0.0 0.0 1.0 ... 0.38 2.0 355.0]
 [0.0 0.0 1.0 ... 1.3732214298586618 1.0 365.0]
 ...
 [0.0 0.0 1.0 ... 1.3732214298586618 1.0 27.0]
 [0.0 0.0 1.0 ... 1.3732214298586618 6.0 2.0]
 [0.0 0.0 1.0 ... 1.3732214298586618 1.0 23.0]]


In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)


In [63]:
print(x_train)

[[0.0 0.0 1.0 ... 4.07 2.0 238.0]
 [0.0 0.0 1.0 ... 1.3732214298586618 1.0 317.0]
 [0.0 0.0 0.0 ... 1.3732214298586618 3.0 365.0]
 ...
 [0.0 1.0 0.0 ... 1.31 1.0 8.0]
 [0.0 1.0 0.0 ... 2.03 1.0 327.0]
 [0.0 1.0 0.0 ... 4.65 3.0 342.0]]


In [64]:
print(y_train)

[1 1 0 ... 1 1 1]


In [65]:
print(x_test)

[[0.0 0.0 0.0 ... 1.3732214298586618 2.0 66.0]
 [0.0 0.0 0.0 ... 1.3732214298586618 1.0 282.0]
 [0.0 1.0 0.0 ... 2.15 1.0 0.0]
 ...
 [0.0 1.0 0.0 ... 2.69 2.0 136.0]
 [0.0 1.0 0.0 ... 1.12 2.0 77.0]
 [0.0 0.0 0.0 ... 0.5 103.0 269.0]]


In [37]:
print(y_test)

[1 0 0 ... 1 1 0]


In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [67]:
print(x_train)

[[-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ...  1.79586049e+00
  -1.55244663e-01  9.58268285e-01]
 [-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ...  1.55318398e-03
  -1.85358971e-01  1.55977073e+00]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ...  1.55318398e-03
  -1.25130355e-01  1.92524057e+00]
 ...
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ... -4.05113276e-02
  -1.85358971e-01 -7.92941363e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  4.38542189e-01
  -1.85358971e-01  1.63591028e+00]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  2.18176471e+00
  -1.25130355e-01  1.75011960e+00]]


In [68]:
print(x_test)

[[-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ...  1.55318398e-03
  -1.55244663e-01 -3.51331973e-01]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ...  1.55318398e-03
  -1.85358971e-01  1.29328230e+00]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  5.18384442e-01
  -1.85358971e-01 -8.53853003e-01]
 ...
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  8.77674580e-01
  -1.55244663e-01  1.81644876e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ... -1.66928228e-01
  -1.55244663e-01 -2.67578468e-01]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ... -5.79446534e-01
   2.88630045e+00  1.19430089e+00]]


In [69]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [81]:
print(classifier.predict(sc.transform([2539,2787,0.0,1.0,0.0,40.64749,-73.97237,149,1,9,0.21,6,365])))

ValueError: ignored

In [71]:
print(x_test)

[[-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ...  1.55318398e-03
  -1.55244663e-01 -3.51331973e-01]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ...  1.55318398e-03
  -1.85358971e-01  1.29328230e+00]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  5.18384442e-01
  -1.85358971e-01 -8.53853003e-01]
 ...
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  8.77674580e-01
  -1.55244663e-01  1.81644876e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ... -1.66928228e-01
  -1.55244663e-01 -2.67578468e-01]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ... -5.79446534e-01
   2.88630045e+00  1.19430089e+00]]


In [72]:
print(x_train)

[[-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ...  1.79586049e+00
  -1.55244663e-01  9.58268285e-01]
 [-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ...  1.55318398e-03
  -1.85358971e-01  1.55977073e+00]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ...  1.55318398e-03
  -1.25130355e-01  1.92524057e+00]
 ...
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ... -4.05113276e-02
  -1.85358971e-01 -7.92941363e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  4.38542189e-01
  -1.85358971e-01  1.63591028e+00]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  2.18176471e+00
  -1.25130355e-01  1.75011960e+00]]


In [73]:
print(x_train)

[[-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ...  1.79586049e+00
  -1.55244663e-01  9.58268285e-01]
 [-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ...  1.55318398e-03
  -1.85358971e-01  1.55977073e+00]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ...  1.55318398e-03
  -1.25130355e-01  1.92524057e+00]
 ...
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ... -4.05113276e-02
  -1.85358971e-01 -7.92941363e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  4.38542189e-01
  -1.85358971e-01  1.63591028e+00]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  2.18176471e+00
  -1.25130355e-01  1.75011960e+00]]


In [74]:
y_pred = classifier.predict(x_test)
print(y_pred)
print(y_test)

[1 1 0 ... 0 0 1]
[1 0 0 ... 1 1 0]


In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1831 2392]
 [2344 3212]]


0.5156969015236732