In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [111]:
dataset=pd.read_csv(" Airbnb.csv")

In [112]:
print(dataset)

             id                                               name   host_id  \
0          2539                 Clean & quiet apt home by the park      2787   
1          2595                              Skylit Midtown Castle      2845   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632   
3          3831                    Cozy Entire Floor of Brownstone      4869   
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192   
...         ...                                                ...       ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441   
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630   
48892  36485431            Sunny Studio at Historical Neighborhood  23492952   
48893  36485609               43rd St. Time Square-cozy single bed  30985759   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814   

      neighbourhood_group  latitude  lo

In [113]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-6].values
print(x)
print(y)

[[2539 'Clean & quiet apt home by the park' 2787 ... 9 0.21 6]
 [2595 'Skylit Midtown Castle' 2845 ... 45 0.38 2]
 [3647 'THE VILLAGE OF HARLEM....NEW YORK !' 4632 ... 0 nan 1]
 ...
 [36485431 'Sunny Studio at Historical Neighborhood' 23492952 ... 0 nan 1]
 [36485609 '43rd St. Time Square-cozy single bed' 30985759 ... 0 nan 6]
 [36487245 "Trendy duplex in the very heart of Hell's Kitchen" 68119814
  ... 0 nan 1]]
[149 225 150 ... 115  55  90]


In [114]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 8:13])
x[:, 8:13] = imputer.transform(x[:, 8:13])


In [115]:
print(x)

[[2539 'Clean & quiet apt home by the park' 2787 ... 9.0 0.21 6.0]
 [2595 'Skylit Midtown Castle' 2845 ... 45.0 0.38 2.0]
 [3647 'THE VILLAGE OF HARLEM....NEW YORK !' 4632 ... 0.0
  1.3732214298586618 1.0]
 ...
 [36485431 'Sunny Studio at Historical Neighborhood' 23492952 ... 0.0
  1.3732214298586618 1.0]
 [36485609 '43rd St. Time Square-cozy single bed' 30985759 ... 0.0
  1.3732214298586618 6.0]
 [36487245 "Trendy duplex in the very heart of Hell's Kitchen" 68119814
  ... 0.0 1.3732214298586618 1.0]]


In [116]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [117]:
print(x)

[[0.0 1.0 0.0 ... 9.0 0.21 6.0]
 [0.0 0.0 1.0 ... 45.0 0.38 2.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]
 ...
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 6.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]]


In [118]:
dataset['price'].describe()

count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [119]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=np.array(le.fit_transform(y))

In [120]:
print(y)

[138 214 139 ... 104  44  79]
