In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [100]:
dataset=pd.read_csv("Airbnb.csv")

In [101]:
print(dataset)

             id   host_id neighbourhood_group  latitude  longitude  price  \
0          2539      2787            Brooklyn  40.64749  -73.97237    149   
1          2595      2845           Manhattan  40.75362  -73.98377    225   
2          3647      4632           Manhattan  40.80902  -73.94190    150   
3          3831      4869            Brooklyn  40.68514  -73.95976     89   
4          5022      7192           Manhattan  40.79851  -73.94399     80   
...         ...       ...                 ...       ...        ...    ...   
48890  36484665   8232441            Brooklyn  40.67853  -73.94995     70   
48891  36485057   6570630            Brooklyn  40.70184  -73.93317     40   
48892  36485431  23492952           Manhattan  40.81475  -73.94867    115   
48893  36485609  30985759           Manhattan  40.75751  -73.99112     55   
48894  36487245  68119814           Manhattan  40.76404  -73.98933     90   

       minimum_nights  number_of_reviews  reviews_per_month  \
0           

In [102]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-6].values
print(x)
print(y)

[[2539 2787 'Brooklyn' ... 9 0.21 6]
 [2595 2845 'Manhattan' ... 45 0.38 2]
 [3647 4632 'Manhattan' ... 0 nan 1]
 ...
 [36485431 23492952 'Manhattan' ... 0 nan 1]
 [36485609 30985759 'Manhattan' ... 0 nan 6]
 [36487245 68119814 'Manhattan' ... 0 nan 1]]
[149 225 150 ... 115  55  90]


In [103]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,5:11])
x[:,5:11] = imputer.transform(x[:, 5:11])


In [104]:
print(x)

[[2539 2787 'Brooklyn' ... 9.0 0.21 6.0]
 [2595 2845 'Manhattan' ... 45.0 0.38 2.0]
 [3647 4632 'Manhattan' ... 0.0 1.3732214298586618 1.0]
 ...
 [36485431 23492952 'Manhattan' ... 0.0 1.3732214298586618 1.0]
 [36485609 30985759 'Manhattan' ... 0.0 1.3732214298586618 6.0]
 [36487245 68119814 'Manhattan' ... 0.0 1.3732214298586618 1.0]]


In [105]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [106]:
print(x)

[[0.0 1.0 0.0 ... 9.0 0.21 6.0]
 [0.0 0.0 1.0 ... 45.0 0.38 2.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]
 ...
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 6.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]]


In [107]:
dataset['price'].describe()


count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [108]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=np.array(le.fit_transform(y))

In [109]:
print(y)

[138 214 139 ... 104  44  79]


In [110]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)


In [111]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[5:11] = sc.fit_transform(x_train[5:11])
x_test[5:11] = sc.transform(x_test[5:11])

In [113]:
print(x_test)

[[0.0 0.0 0.0 ... 0.0 1.3732214298586618 2.0]
 [0.0 0.0 0.0 ... 0.0 1.3732214298586618 1.0]
 [0.0 1.0 0.0 ... 53.0 2.15 1.0]
 ...
 [0.0 1.0 0.0 ... 263.0 2.69 2.0]
 [0.0 1.0 0.0 ... 53.0 1.12 2.0]
 [0.0 0.0 0.0 ... 2.0 0.5 103.0]]


In [114]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)


DecisionTreeClassifier(criterion='entropy', random_state=0)

In [115]:
x_predict = np.array(x_test[:,:])
print(classifier.predict((x_predict)))

accuracy = classifier.score(x_test,y_test)
print(accuracy)

[ 49 239  69 ...  39  94  39]
0.99171694447285


In [116]:
print(y_test)

[ 49 239  69 ...  39  94  39]


In [117]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()