In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
dataset=pd.read_csv("Airbnb.csv")

In [54]:
print(dataset)

             id   host_id neighbourhood_group  latitude  longitude  price  \
0          2539      2787            Brooklyn  40.64749  -73.97237    149   
1          2595      2845           Manhattan  40.75362  -73.98377    225   
2          3647      4632           Manhattan  40.80902  -73.94190    150   
3          3831      4869            Brooklyn  40.68514  -73.95976     89   
4          5022      7192           Manhattan  40.79851  -73.94399     80   
...         ...       ...                 ...       ...        ...    ...   
48890  36484665   8232441            Brooklyn  40.67853  -73.94995     70   
48891  36485057   6570630            Brooklyn  40.70184  -73.93317     40   
48892  36485431  23492952           Manhattan  40.81475  -73.94867    115   
48893  36485609  30985759           Manhattan  40.75751  -73.99112     55   
48894  36487245  68119814           Manhattan  40.76404  -73.98933     90   

       minimum_nights  number_of_reviews  reviews_per_month  \
0           

In [55]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,5].values
print(x)
print(y)

[[2539 2787 'Brooklyn' ... 9 0.21 6]
 [2595 2845 'Manhattan' ... 45 0.38 2]
 [3647 4632 'Manhattan' ... 0 nan 1]
 ...
 [36485431 23492952 'Manhattan' ... 0 nan 1]
 [36485609 30985759 'Manhattan' ... 0 nan 6]
 [36487245 68119814 'Manhattan' ... 0 nan 1]]
[149 225 150 ... 115  55  90]


In [56]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,5:11])
x[:,5:11] = imputer.transform(x[:, 5:11])

In [57]:
print(x)

[[2539 2787 'Brooklyn' ... 9.0 0.21 6.0]
 [2595 2845 'Manhattan' ... 45.0 0.38 2.0]
 [3647 4632 'Manhattan' ... 0.0 1.3732214298586618 1.0]
 ...
 [36485431 23492952 'Manhattan' ... 0.0 1.3732214298586618 1.0]
 [36485609 30985759 'Manhattan' ... 0.0 1.3732214298586618 6.0]
 [36487245 68119814 'Manhattan' ... 0.0 1.3732214298586618 1.0]]


In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [59]:
print(x)

[[0.0 1.0 0.0 ... 9.0 0.21 6.0]
 [0.0 0.0 1.0 ... 45.0 0.38 2.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]
 ...
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 6.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]]


In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)


In [61]:
print(x_train)

[[0.0 0.0 1.0 ... 116.0 4.07 2.0]
 [0.0 0.0 1.0 ... 0.0 1.3732214298586618 1.0]
 [0.0 0.0 0.0 ... 0.0 1.3732214298586618 3.0]
 ...
 [0.0 1.0 0.0 ... 78.0 1.31 1.0]
 [0.0 1.0 0.0 ... 84.0 2.03 1.0]
 [0.0 1.0 0.0 ... 59.0 4.65 3.0]]


In [62]:
print(y_train)

[ 73 189 800 ... 115 330  60]


In [63]:
print(x_test)

[[0.0 0.0 0.0 ... 0.0 1.3732214298586618 2.0]
 [0.0 0.0 0.0 ... 0.0 1.3732214298586618 1.0]
 [0.0 1.0 0.0 ... 53.0 2.15 1.0]
 ...
 [0.0 1.0 0.0 ... 263.0 2.69 2.0]
 [0.0 1.0 0.0 ... 53.0 1.12 2.0]
 [0.0 0.0 0.0 ... 2.0 0.5 103.0]]


In [64]:
print(y_test)

[ 60 250  80 ...  50 105  50]


In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [43]:
print(x_train)

[[-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ...  2.12585413e+00
   1.79586049e+00 -1.55244663e-01]
 [-1.51176894e-01 -8.35883679e-01  1.12110031e+00 ... -5.25297027e-01
   1.55318398e-03 -1.85358971e-01]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ... -5.25297027e-01
   1.55318398e-03 -1.25130355e-01]
 ...
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  1.25737358e+00
  -4.05113276e-02 -1.85358971e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  1.39450209e+00
   4.38542189e-01 -1.85358971e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  8.23133304e-01
   2.18176471e+00 -1.25130355e-01]]


In [66]:
print(x_test)

[[-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ... -5.25297027e-01
   1.55318398e-03 -1.55244663e-01]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ... -5.25297027e-01
   1.55318398e-03 -1.85358971e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  6.86004796e-01
   5.18384442e-01 -1.85358971e-01]
 ...
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  5.48550259e+00
   8.77674580e-01 -1.55244663e-01]
 [-1.51176894e-01  1.19633871e+00 -8.91980841e-01 ...  6.86004796e-01
  -1.66928228e-01 -1.55244663e-01]
 [-1.51176894e-01 -8.35883679e-01 -8.91980841e-01 ... -4.79587525e-01
  -5.79446534e-01  2.88630045e+00]]


In [67]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [68]:
print(classifier.predict(sc.transform([[60,87000]])))

ValueError: ignored

In [69]:
y_pred = classifier.predict(x_test)
print(y_pred)
print(y_test)

[ 60 250  80 ...  50 105  50]
[ 60 250  80 ...  50 105  50]


In [70]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


0.9926372839758667